# Generated by Django 4.2.4 on 2023-10-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_customer_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctors_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
