# Generated by Django 4.2.4 on 2023-10-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
    ]
