# Generated by Django 4.2.4 on 2023-10-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_remove_appointment_time_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
    ]
